import { useCallback, useEffect, useState } from 'react'
import './App.css'

const API_URL = (import.meta.env.VITE_API_URL || 'http://localhost:5050/api').replace(/\/$/, '')
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'

function BookingsTable({ bookings }) {
  return <section className="table-card"><div className="table-heading"><h2>All bookings</h2><span>{bookings.length} records</span></div>{bookings.length === 0 ? <p className="empty">No bookings yet.</p> : <div className="table-scroll"><table><thead><tr><th>Date</th><th>Time</th><th>Table</th><th>Guest email</th><th>Created</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td>{booking.date}</td><td>{booking.timeSlot}</td><td>Table {booking.tableNumber}</td><td>{booking.emailId}</td><td>{formatDate(booking.createdAt)}</td></tr>)}</tbody></table></div>}</section>
}

function LedgerTable({ entries }) {
  return <section className="table-card"><div className="table-heading"><h2>Booking ledger</h2><span>Activity records</span></div>{entries.length === 0 ? <p className="empty">No ledger activity yet.</p> : <div className="table-scroll"><table><thead><tr><th>Recorded at</th><th>Entry</th><th>Guest</th><th>Details</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td>{formatDate(entry.occurredAt)}</td><td><span className="badge">{entry.type}</span></td><td>{entry.guestEmail}</td><td>{entry.detail}</td></tr>)}</tbody></table></div>}</section>
}

function App() {
  const [emailId, setEmailId] = useState(''); const [password, setPassword] = useState(''); const [token, setToken] = useState(() => localStorage.getItem('diceDynastyOwnerToken')); const [bookings, setBookings] = useState([]); const [ledger, setLedger] = useState([]); const [activeTab, setActiveTab] = useState('bookings'); const [error, setError] = useState(''); const [loading, setLoading] = useState(() => Boolean(localStorage.getItem('diceDynastyOwnerToken')))
  const loadDashboard = useCallback(async (showSpinner = true) => { if (showSpinner) setLoading(true); setError(''); try { const headers = { Authorization: `Bearer ${token}` }; const [bookingsResponse, ledgerResponse] = await Promise.all([fetch(`${API_URL}/bookings/owner`, { headers }), fetch(`${API_URL}/bookings/owner/ledger`, { headers })]); const bookingsData = await bookingsResponse.json(); const ledgerData = await ledgerResponse.json(); if (!bookingsResponse.ok) throw new Error(bookingsData.message || 'Could not load bookings'); if (!ledgerResponse.ok) throw new Error(ledgerData.message || 'Could not load ledger'); setBookings(bookingsData.bookings || []); setLedger(ledgerData.entries || []) } catch (dashboardError) { setError(dashboardError.message) } finally { setLoading(false) } }, [token])
  useEffect(() => { if (token) void Promise.resolve().then(() => loadDashboard(false)) }, [token, loadDashboard])
  async function handleLogin(event) { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${API_URL}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ emailId, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Could not sign in'); localStorage.setItem('diceDynastyOwnerToken', data.token); setToken(data.token) } catch (loginError) { setError(loginError.message); setLoading(false) } }
  function logout() { localStorage.removeItem('diceDynastyOwnerToken'); setToken(null); setBookings([]); setLedger([]); setError('') }
  if (!token) return <main className="login-page"><form className="login-card" onSubmit={handleLogin}><p className="eyebrow">Dice Dynasty</p><h1>Owner console</h1><p>Sign in with the email configured as <code>ADMIN_EMAIL</code>.</p><label>Email<input type="email" value={emailId} onChange={(event) => setEmailId(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="error">{error}</p>}<button disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form></main>
  return <main className="dashboard"><header><div><p className="eyebrow">Dice Dynasty</p><h1>Owner console</h1></div><button className="secondary" onClick={logout}>Sign out</button></header><section className="stats"><article><span>Total bookings</span><strong>{bookings.length}</strong></article><article><span>Today’s bookings</span><strong>{bookings.filter((booking) => booking.date === new Date().toISOString().slice(0, 10)).length}</strong></article><article><span>Ledger entries</span><strong>{ledger.length}</strong></article></section><nav><button className={activeTab === 'bookings' ? 'active' : ''} onClick={() => setActiveTab('bookings')}>Bookings</button><button className={activeTab === 'ledger' ? 'active' : ''} onClick={() => setActiveTab('ledger')}>Booking ledger</button><button className="refresh" onClick={loadDashboard} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button></nav>{error && <p className="error">{error}</p>}{activeTab === 'bookings' ? <BookingsTable bookings={bookings} /> : <LedgerTable entries={ledger} />}</main>
}
export default App
